// Generates .design-sync/entry.js — the library entry the design-sync converter
// bundles. This repo is a Next.js app with no published dist/, so the entry is a
// barrel that re-exports every component from components/**/*.js.
//
// Regenerate after adding/removing/renaming components:
//   node .design-sync/make-entry.mjs
//
// It also prints a componentSrcMap block for .design-sync/config.json — the
// converter's discovery only globs .tsx/.jsx, so .js components must be pinned.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const SRC = join(ROOT, 'components');

const walk = (d, out = []) => {
  for (const n of readdirSync(d).sort()) {
    const p = join(d, n);
    statSync(p).isDirectory() ? walk(p, out) : n.endsWith('.js') && out.push(p);
  }
  return out;
};

const isComponent = (n) => /^[A-Z][A-Za-z0-9]*$/.test(n);

const lines = [];
const srcMap = {};

for (const file of walk(SRC)) {
  const text = readFileSync(file, 'utf8');
  // Import specifiers resolve relative to entry.js (in .design-sync/), while
  // componentSrcMap paths are package-relative (repo root). Different bases.
  const rel = relative(HERE, file).split('\\').join('/');

  const named = [...text.matchAll(/^export\s+(?:async\s+)?(?:function|const|class)\s+([A-Za-z_$][\w$]*)/gm)]
    .map((m) => m[1])
    .filter(isComponent);
  const defMatch = /^export\s+default\s+(?:function\s+([A-Za-z_$][\w$]*)|([A-Za-z_$][\w$]*))/m.exec(text);
  const defName = defMatch?.[1] ?? defMatch?.[2] ?? null;

  // Context hooks (useAuth, useUser, useToast) are part of the design system's
  // real API — a design built on AuthProvider/ToastProvider needs them — so they
  // are exported into window.<global> alongside the components. They are NOT
  // added to srcMap: only PascalCase names are components, and a hook must not
  // become a card.
  const hooks = [...text.matchAll(/^export\s+(?:async\s+)?(?:function|const)\s+(use[A-Z][\w$]*)/gm)].map((m) => m[1]);

  if (named.length || hooks.length) {
    lines.push(`export { ${[...named, ...hooks].join(', ')} } from ${JSON.stringify(rel)};`);
    for (const n of named) srcMap[n] = relative(ROOT, file).split('\\').join('/');
  }
  if (defName && isComponent(defName)) {
    lines.push(`export { default as ${defName} } from ${JSON.stringify(rel)};`);
    srcMap[defName] = relative(ROOT, file).split('\\').join('/');
  }
}

// The env shim must be the FIRST import: ES module evaluation follows import
// order, so this runs before any component module body executes (several read
// process.env at module scope, which does not exist in a browser IIFE).
const banner =
  `// GENERATED by .design-sync/make-entry.mjs — do not edit by hand.\n` +
  `// Library entry for design-sync: re-exports every component in components/.\n` +
  `import "./env-shim.js";\n`;
writeFileSync(join(HERE, 'entry.js'), banner + lines.join('\n') + '\n');

console.error(`wrote .design-sync/entry.js — ${Object.keys(srcMap).length} components`);
console.log(JSON.stringify({ componentSrcMap: Object.fromEntries(Object.entries(srcMap).sort()) }, null, 2));
